name: YAML validation

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  yaml-validation:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: YAML Lint
      uses: ibiqlik/action-yamllint@v1.0.0
      with:
        ## File(s) or Directory, separate by space if multiple files or folder are specified
        file_or_dir: modelFiles/
        ## Custom configuration (as YAML source)
        config_data: "{extends: default, rules: {line-length: disable}}"
        ## Format for parsing output [parsable,standard,colored,auto]
        # format: # optional, default is colored
        ## Return non-zero exit code on warnings as well as errors
        # strict: # optional, default is false

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Import with cobrapy
      run: |
        pip install cobra
        python -c "import cobra ; cobra.io.load_yaml_model('modelFiles/yml/HumanGEM.yml')"